info:
  name: Login project
  artifact: '@project.artifactId@'
  version: '@project.version@'

spring:
  application:
    name: login
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:./data/login_db
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:
